sudo: false
language: node_js
node_js:
- '12'
branches:
  only:
  - main
cache:
  directories:
  - node_modules
before_install:
- cd PartnerMeServer
- npm update
install:
- npm install
script:
- cd PartnerMeServer
- npm test